ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: "$PORT:8080"
postgres:
  auth:
    username: "$DB_USER:postgres"
    password: "$DB_PASSWORD:postgres"
  connection:
    host: "$HOST:localhost"
    port: "$PORT:5432"
  database: "$DB_NAME:backend"
crypto:
  bcrypt:
    rounds: "$BCRYPT_ROUNDS:12"
  jwt:
    secret: "$JWT_SECRET:verySecret123!"
    issuer: "$JWT_ISSUER:backend-iss"
    expirySeconds:
      access: "$JWT_ACCESS_EXP:300"
      refresh: "$JWT_REFRESH_EXP:86400"